### ISSUE TITLE
Release message and module 'datapane' has no attribute 'Report' with version 0.16.1

### ISSUE THREAD

**Issue by ThomasBouche** [datapane/datapane#355]
Hello, 
I have a method to generate a report write like this:
```
def execute_report() -> dp.Report:
```
I have this error message with the new version (0.16.1) of datapane, is it normal?
![image](https://user-images.githubusercontent.com/53937041/225594393-5dc64800-8d78-426e-b5a8-8640b8331b30.png)

It works with version 0.15.5

Moreover, I can't easily find what's in the evolutions of new datapane releases on github.
Where do you publish them?

I know you have a Discord, but I don't have access to Discord at work

**Comment by shahinrostami** [comment]
Hi @ThomasBouche!

The updated API for Reports can be found in our docs: https://docs.datapane.com/reference/reports/. There's also a working example here https://docs.datapane.com/features/reports/.

We have a release notes page (https://docs.datapane.com/releasenotes/)  but it needs to be updated.

Please let us know how you get on or if there's anything else!

**Comment by ThomasBouche** [comment]
Hello,
reading the documentation, I don't find it clear if I can keep the dp.Report typing or not

**Comment by mands** [comment]
Hi @ThomasBouche - sorry for the lack of clarity - the docs have since been updated - see https://docs.datapane.com and our examples repo (github.com/datapane/examples) for more information.

`dp.Report` has indeed been deprecated, instead you can use `dp.save_report` and pass it in your blocks, either directly, or by using `dp.View` similar to how you used `dp.Report` previously, e.g.

```python
view = dp.View(df, dp.Text("My Dataframe"))
dp.save_report(view, name="report.html")
```
